In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
df = pd.read_csv('employees.csv')
df

   ID     Name  Age Department  Salary Joining_Date
0   1    Alice   25         HR   50000   2019-03-15
1   2      Bob   30         IT   60000   2018-07-23
2   3  Charlie   35    Finance   70000   2017-05-19
3   4    David   40         IT   80000   2016-08-01
4   5      Eve   29         HR   65000   2020-01-12
5   6    Frank   33    Finance   72000   2018-11-03
6   7    Grace   28  Marketing   48000   2021-06-21
7   8     Hank   45         IT   90000   2015-09-14
8   9      Ivy   31    Finance   71000   2019-10-10
9  10     Jack   22  Marketing   92000   2017-12-05

In [3]:
print('DF head')

df.head(3)

DF head

   ID     Name  Age Department  Salary Joining_Date
0   1    Alice   25         HR   50000   2019-03-15
1   2      Bob   30         IT   60000   2018-07-23
2   3  Charlie   35    Finance   70000   2017-05-19

In [4]:
print('DF tail')

df.tail(3)

DF tail

   ID  Name  Age Department  Salary Joining_Date
7   8  Hank   45         IT   90000   2015-09-14
8   9   Ivy   31    Finance   71000   2019-10-10
9  10  Jack   22  Marketing   92000   2017-12-05

In [5]:
print('DF info')

df.info()

DF info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            10 non-null     int64
 1   Name          10 non-null     object
 2   Age           10 non-null     int64
 3   Department    10 non-null     object
 4   Salary        10 non-null     int64
 5   Joining_Date  10 non-null     object
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [6]:
print('DF shape, how many columns and rows')

df.shape

DF shape, how many columns and rows

(10, 6)

In [7]:
print('Describe, some stadistics: Age and Salary')

df.describe()

Describe, some stadistics: Age and Salary

             ID      Age        Salary
count  10.00000  10.0000     10.000000
mean    5.50000  31.8000  69800.000000
std     3.02765   6.8443  14898.172893
min     1.00000  22.0000  48000.000000
25%     3.25000  28.2500  61250.000000
50%     5.50000  30.5000  70500.000000
75%     7.75000  34.5000  78000.000000
max    10.00000  45.0000  92000.000000

In [8]:
print('Data types')

df.dtypes

Data types

ID               int64
Name            object
Age              int64
Department      object
Salary           int64
Joining_Date    object
dtype: object

In [9]:
print('Select a column')

df['Name']

Select a column

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
5      Frank
6      Grace
7       Hank
8        Ivy
9       Jack
Name: Name, dtype: object

In [10]:
print('Print 2 columns from an specific index')

df[['Name', 'Salary']].loc[0:3]

Print 2 columns from an specific index

      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   70000
3    David   80000

In [11]:
print('Direct index searching')

df.iloc[2,3]

Direct index searching

'Finance'

In [12]:
print('Set ID as index')

df.set_index('ID')

Set ID as index

       Name  Age Department  Salary Joining_Date
ID
1     Alice   25         HR   50000   2019-03-15
2       Bob   30         IT   60000   2018-07-23
3   Charlie   35    Finance   70000   2017-05-19
4     David   40         IT   80000   2016-08-01
5       Eve   29         HR   65000   2020-01-12
6     Frank   33    Finance   72000   2018-11-03
7     Grace   28  Marketing   48000   2021-06-21
8      Hank   45         IT   90000   2015-09-14
9       Ivy   31    Finance   71000   2019-10-10
10     Jack   22  Marketing   92000   2017-12-05

In [13]:
print('Reset index to the original value')

df.reset_index()

Reset index to the original value

   index  ID     Name  Age Department  Salary Joining_Date
0      0   1    Alice   25         HR   50000   2019-03-15
1      1   2      Bob   30         IT   60000   2018-07-23
2      2   3  Charlie   35    Finance   70000   2017-05-19
3      3   4    David   40         IT   80000   2016-08-01
4      4   5      Eve   29         HR   65000   2020-01-12
5      5   6    Frank   33    Finance   72000   2018-11-03
6      6   7    Grace   28  Marketing   48000   2021-06-21
7      7   8     Hank   45         IT   90000   2015-09-14
8      8   9      Ivy   31    Finance   71000   2019-10-10
9      9  10     Jack   22  Marketing   92000   2017-12-05

In [14]:
print('Order employees by salary from biggest to smallest')

df.sort_values('Salary', ascending=False)

Order employees by salary from biggest to smallest

   ID     Name  Age Department  Salary Joining_Date
9  10     Jack   22  Marketing   92000   2017-12-05
7   8     Hank   45         IT   90000   2015-09-14
3   4    David   40         IT   80000   2016-08-01
5   6    Frank   33    Finance   72000   2018-11-03
8   9      Ivy   31    Finance   71000   2019-10-10
2   3  Charlie   35    Finance   70000   2017-05-19
4   5      Eve   29         HR   65000   2020-01-12
1   2      Bob   30         IT   60000   2018-07-23
0   1    Alice   25         HR   50000   2019-03-15
6   7    Grace   28  Marketing   48000   2021-06-21

In [15]:
print('Order by inverted index')

df.sort_index(ascending=False)

Order by inverted index

   ID     Name  Age Department  Salary Joining_Date
9  10     Jack   22  Marketing   92000   2017-12-05
8   9      Ivy   31    Finance   71000   2019-10-10
7   8     Hank   45         IT   90000   2015-09-14
6   7    Grace   28  Marketing   48000   2021-06-21
5   6    Frank   33    Finance   72000   2018-11-03
4   5      Eve   29         HR   65000   2020-01-12
3   4    David   40         IT   80000   2016-08-01
2   3  Charlie   35    Finance   70000   2017-05-19
1   2      Bob   30         IT   60000   2018-07-23
0   1    Alice   25         HR   50000   2019-03-15

In [16]:
print('Group by average salary by department')

df.groupby('Department')['Salary'].mean()

Group by average salary by department

Department
Finance      71000.000000
HR           57500.000000
IT           76666.666667
Marketing    70000.000000
Name: Salary, dtype: float64

In [17]:
print('Max age and total salary')

df.agg({'Age': 'max', 'Salary': 'sum'})

Max age and total salary

Age           45
Salary    698000
dtype: int64

In [18]:
print('New column that adds 5 to each age')

df['Age_plus_5'] = df['Age'].apply(lambda x: x + 5)
df

New column that adds 5 to each age

   ID     Name  Age Department  Salary Joining_Date  Age_plus_5
0   1    Alice   25         HR   50000   2019-03-15          30
1   2      Bob   30         IT   60000   2018-07-23          35
2   3  Charlie   35    Finance   70000   2017-05-19          40
3   4    David   40         IT   80000   2016-08-01          45
4   5      Eve   29         HR   65000   2020-01-12          34
5   6    Frank   33    Finance   72000   2018-11-03          38
6   7    Grace   28  Marketing   48000   2021-06-21          33
7   8     Hank   45         IT   90000   2015-09-14          50
8   9      Ivy   31    Finance   71000   2019-10-10          36
9  10     Jack   22  Marketing   92000   2017-12-05          27

In [19]:
print('Convert all the text of Name and Department to upper case')

df[['Name','Department']] = df[['Name','Department']].map(str.upper)
df

Convert all the text of Name and Department to upper case

   ID     Name  Age Department  Salary Joining_Date  Age_plus_5
0   1    ALICE   25         HR   50000   2019-03-15          30
1   2      BOB   30         IT   60000   2018-07-23          35
2   3  CHARLIE   35    FINANCE   70000   2017-05-19          40
3   4    DAVID   40         IT   80000   2016-08-01          45
4   5      EVE   29         HR   65000   2020-01-12          34
5   6    FRANK   33    FINANCE   72000   2018-11-03          38
6   7    GRACE   28  MARKETING   48000   2021-06-21          33
7   8     HANK   45         IT   90000   2015-09-14          50
8   9      IVY   31    FINANCE   71000   2019-10-10          36
9  10     JACK   22  MARKETING   92000   2017-12-05          27

In [20]:
print('Check if NULL in dataset')

df.loc[len(df)] = [len(df),'Carlos', 22, 'IT', 60000, None, None]

df.isnull()

Check if NULL in dataset

       ID   Name    Age  Department  Salary  Joining_Date  Age_plus_5
0   False  False  False       False   False         False       False
1   False  False  False       False   False         False       False
2   False  False  False       False   False         False       False
3   False  False  False       False   False         False       False
4   False  False  False       False   False         False       False
5   False  False  False       False   False         False       False
6   False  False  False       False   False         False       False
7   False  False  False       False   False         False       False
8   False  False  False       False   False         False       False
9   False  False  False       False   False         False       False
10  False  False  False       False   False          True        True

In [21]:
print('Delete rows with NULL values')

print(df)

df = df.dropna()

df

Delete rows with NULL values
    ID     Name  Age Department  Salary Joining_Date Age_plus_5
0    1    ALICE   25         HR   50000   2019-03-15         30
1    2      BOB   30         IT   60000   2018-07-23         35
2    3  CHARLIE   35    FINANCE   70000   2017-05-19         40
3    4    DAVID   40         IT   80000   2016-08-01         45
4    5      EVE   29         HR   65000   2020-01-12         34
5    6    FRANK   33    FINANCE   72000   2018-11-03         38
6    7    GRACE   28  MARKETING   48000   2021-06-21         33
7    8     HANK   45         IT   90000   2015-09-14         50
8    9      IVY   31    FINANCE   71000   2019-10-10         36
9   10     JACK   22  MARKETING   92000   2017-12-05         27
10  10   Carlos   22         IT   60000         None       None

   ID     Name  Age Department  Salary Joining_Date Age_plus_5
0   1    ALICE   25         HR   50000   2019-03-15         30
1   2      BOB   30         IT   60000   2018-07-23         35
2   3  CHARLIE   35    FINANCE   70000   2017-05-19         40
3   4    DAVID   40         IT   80000   2016-08-01         45
4   5      EVE   29         HR   65000   2020-01-12         34
5   6    FRANK   33    FINANCE   72000   2018-11-03         38
6   7    GRACE   28  MARKETING   48000   2021-06-21         33
7   8     HANK   45         IT   90000   2015-09-14         50
8   9      IVY   31    FINANCE   71000   2019-10-10         36
9  10     JACK   22  MARKETING   92000   2017-12-05         27

In [22]:
print('Fill NULL salaries with 0')

df.loc[len(df)] = [len(df),'MAX', 22, 'IT', None, '2022-06-21', 27]

print(df)

df = df.fillna({'Salary': 0})

df

Fill NULL salaries with 0
    ID     Name  Age Department Salary Joining_Date Age_plus_5
0    1    ALICE   25         HR  50000   2019-03-15         30
1    2      BOB   30         IT  60000   2018-07-23         35
2    3  CHARLIE   35    FINANCE  70000   2017-05-19         40
3    4    DAVID   40         IT  80000   2016-08-01         45
4    5      EVE   29         HR  65000   2020-01-12         34
5    6    FRANK   33    FINANCE  72000   2018-11-03         38
6    7    GRACE   28  MARKETING  48000   2021-06-21         33
7    8     HANK   45         IT  90000   2015-09-14         50
8    9      IVY   31    FINANCE  71000   2019-10-10         36
9   10     JACK   22  MARKETING  92000   2017-12-05         27
10  10      MAX   22         IT   None   2022-06-21         27

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_26172\3726741353.py:7: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna({'Salary': 0})

    ID     Name  Age Department  Salary Joining_Date Age_plus_5
0    1    ALICE   25         HR   50000   2019-03-15         30
1    2      BOB   30         IT   60000   2018-07-23         35
2    3  CHARLIE   35    FINANCE   70000   2017-05-19         40
3    4    DAVID   40         IT   80000   2016-08-01         45
4    5      EVE   29         HR   65000   2020-01-12         34
5    6    FRANK   33    FINANCE   72000   2018-11-03         38
6    7    GRACE   28  MARKETING   48000   2021-06-21         33
7    8     HANK   45         IT   90000   2015-09-14         50
8    9      IVY   31    FINANCE   71000   2019-10-10         36
9   10     JACK   22  MARKETING   92000   2017-12-05         27
10  10      MAX   22         IT       0   2022-06-21         27

In [23]:
print('Drop column')

df = df.drop(['Age_plus_5'], axis=1)
df

Drop column

    ID     Name  Age Department  Salary Joining_Date
0    1    ALICE   25         HR   50000   2019-03-15
1    2      BOB   30         IT   60000   2018-07-23
2    3  CHARLIE   35    FINANCE   70000   2017-05-19
3    4    DAVID   40         IT   80000   2016-08-01
4    5      EVE   29         HR   65000   2020-01-12
5    6    FRANK   33    FINANCE   72000   2018-11-03
6    7    GRACE   28  MARKETING   48000   2021-06-21
7    8     HANK   45         IT   90000   2015-09-14
8    9      IVY   31    FINANCE   71000   2019-10-10
9   10     JACK   22  MARKETING   92000   2017-12-05
10  10      MAX   22         IT       0   2022-06-21

In [24]:
print('Rename column')

df = df.rename({'Salary': 'Annual_Salary'}, axis=1)
df

Rename column

    ID     Name  Age Department  Annual_Salary Joining_Date
0    1    ALICE   25         HR          50000   2019-03-15
1    2      BOB   30         IT          60000   2018-07-23
2    3  CHARLIE   35    FINANCE          70000   2017-05-19
3    4    DAVID   40         IT          80000   2016-08-01
4    5      EVE   29         HR          65000   2020-01-12
5    6    FRANK   33    FINANCE          72000   2018-11-03
6    7    GRACE   28  MARKETING          48000   2021-06-21
7    8     HANK   45         IT          90000   2015-09-14
8    9      IVY   31    FINANCE          71000   2019-10-10
9   10     JACK   22  MARKETING          92000   2017-12-05
10  10      MAX   22         IT              0   2022-06-21

In [25]:
print('Merge')

dept_codes = pd.DataFrame({
    "Department": ["HR","IT","FINANCE","MARKETING"],
    "D-Code": [1,2,3,4]
})
merged = df.merge(dept_codes, on="Department")
merged

Merge

    ID     Name  Age Department  Annual_Salary Joining_Date  D-Code
0    1    ALICE   25         HR          50000   2019-03-15       1
1    2      BOB   30         IT          60000   2018-07-23       2
2    3  CHARLIE   35    FINANCE          70000   2017-05-19       3
3    4    DAVID   40         IT          80000   2016-08-01       2
4    5      EVE   29         HR          65000   2020-01-12       1
5    6    FRANK   33    FINANCE          72000   2018-11-03       3
6    7    GRACE   28  MARKETING          48000   2021-06-21       4
7    8     HANK   45         IT          90000   2015-09-14       2
8    9      IVY   31    FINANCE          71000   2019-10-10       3
9   10     JACK   22  MARKETING          92000   2017-12-05       4
10  10      MAX   22         IT              0   2022-06-21       2

In [26]:
print('Concat with itself, duplicate employees')

df_concat = pd.concat([df,df])
df_concat

Concat with itself, duplicate employees

    ID     Name  Age Department  Annual_Salary Joining_Date
0    1    ALICE   25         HR          50000   2019-03-15
1    2      BOB   30         IT          60000   2018-07-23
2    3  CHARLIE   35    FINANCE          70000   2017-05-19
3    4    DAVID   40         IT          80000   2016-08-01
4    5      EVE   29         HR          65000   2020-01-12
5    6    FRANK   33    FINANCE          72000   2018-11-03
6    7    GRACE   28  MARKETING          48000   2021-06-21
7    8     HANK   45         IT          90000   2015-09-14
8    9      IVY   31    FINANCE          71000   2019-10-10
9   10     JACK   22  MARKETING          92000   2017-12-05
10  10      MAX   22         IT              0   2022-06-21
0    1    ALICE   25         HR          50000   2019-03-15
1    2      BOB   30         IT          60000   2018-07-23
2    3  CHARLIE   35    FINANCE          70000   2017-05-19
3    4    DAVID   40         IT          80000   2016-08-01
4    5      EVE   29         HR          65000   2020-01-12
5    6    FRANK   33    FINANCE          72000   2018-11-03
6    7    GRACE   28  MARKETING          48000   2021-06-21
7    8     HANK   45         IT          90000   2015-09-14
8    9      IVY   31    FINANCE          71000   2019-10-10
9   10     JACK   22  MARKETING          92000   2017-12-05
10  10      MAX   22         IT              0   2022-06-21

In [27]:
print('Pivot table')

df_pivot = df.pivot_table(values='Annual_Salary', index='Department', aggfunc=np.mean)
df_pivot

Pivot table

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_26172\3562185983.py:3: FutureWarning: The provided callable <function mean at 0x00000186D52ACB80> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df_pivot = df.pivot_table(values='Annual_Salary', index='Department', aggfunc=np.mean)

            Annual_Salary
Department
FINANCE           71000.0
HR                57500.0
IT                57500.0
MARKETING         70000.0

In [28]:
print('Melt pivot table')

df_melt = df.melt(df_pivot)
df_melt

Melt pivot table

    Annual_Salary      variable       value
0           50000            ID           1
1           60000            ID           2
2           70000            ID           3
3           80000            ID           4
4           65000            ID           5
5           72000            ID           6
6           48000            ID           7
7           90000            ID           8
8           71000            ID           9
9           92000            ID          10
10              0            ID          10
11          50000          Name       ALICE
12          60000          Name         BOB
13          70000          Name     CHARLIE
14          80000          Name       DAVID
15          65000          Name         EVE
16          72000          Name       FRANK
17          48000          Name       GRACE
18          90000          Name        HANK
19          71000          Name         IVY
20          92000          Name        JACK
21              0          Name         MAX
22          50000           Age          25
23          60000           Age          30
24          70000           Age          35
25          80000           Age          40
26          65000           Age          29
27          72000           Age          33
28          48000           Age          28
29          90000           Age          45
30          71000           Age          31
31          92000           Age          22
32              0           Age          22
33          50000    Department          HR
34          60000    Department          IT
35          70000    Department     FINANCE
36          80000    Department          IT
37          65000    Department          HR
38          72000    Department     FINANCE
39          48000    Department   MARKETING
40          90000    Department          IT
41          71000    Department     FINANCE
42          92000    Department   MARKETING
43              0    Department          IT
44          50000  Joining_Date  2019-03-15
45          60000  Joining_Date  2018-07-23
46          70000  Joining_Date  2017-05-19
47          80000  Joining_Date  2016-08-01
48          65000  Joining_Date  2020-01-12
49          72000  Joining_Date  2018-11-03
50          48000  Joining_Date  2021-06-21
51          90000  Joining_Date  2015-09-14
52          71000  Joining_Date  2019-10-10
53          92000  Joining_Date  2017-12-05
54              0  Joining_Date  2022-06-21

In [29]:
print('How many employees are per department')

print(df.value_counts('Department'))

How many employees are per department
Department
IT           4
FINANCE      3
HR           2
MARKETING    2
Name: count, dtype: int64

In [30]:
print('Unique values per colunm')

df.nunique()

Unique values per colunm

ID               10
Name             11
Age              10
Department        4
Annual_Salary    11
Joining_Date     11
dtype: int64

In [31]:
print('Save transformed CSV')

df.to_csv('employees_new.csv')

Save transformed CSV

In [32]:
print('3 youngest player')

df_sort = df.sort_values('Age')[['Name', 'Age']]
df_sort.head(3)

3 youngest player

     Name  Age
10    MAX   22
9    JACK   22
0   ALICE   25

In [33]:
print('3 youngest player - other way')

df.nsmallest(3, 'Age')[['Name', 'Age']]

3 youngest player - other way

     Name  Age
9    JACK   22
10    MAX   22
0   ALICE   25

In [34]:
print('Employee with higest salary')

df.nlargest(1, 'Annual_Salary')[['Name', 'Annual_Salary']]

Employee with higest salary

   Name  Annual_Salary
9  JACK          92000

In [35]:
print('Employee with higest salary- 2 way')

df.sort_values('Annual_Salary')[['Name', 'Annual_Salary']].tail(1)

Employee with higest salary- 2 way

   Name  Annual_Salary
9  JACK          92000

In [36]:
print('Employee with higest salary- 3 way')

df.loc[df['Annual_Salary'].idxmax(), ['Name', 'Annual_Salary']]

Employee with higest salary- 3 way

Name              JACK
Annual_Salary    92000
Name: 9, dtype: object

In [37]:
print('Employees average age')

print(df['Age'].mean())

Employees average age
30.90909090909091

In [38]:
print('Employees who work in IT')

df[['Name', 'Department']][df['Department'] == 'IT']

Employees who work in IT

     Name Department
1     BOB         IT
3   DAVID         IT
7    HANK         IT
10    MAX         IT

In [39]:
print(' Employeers under 30 years old')

df[['Name', 'Age']][df['Age'] > 30]

 Employeers under 30 years old

      Name  Age
2  CHARLIE   35
3    DAVID   40
5    FRANK   33
7     HANK   45
8      IVY   31

In [40]:
print('Order by join date')

df[['Name', 'Joining_Date']].sort_values('Joining_Date')

Order by join date

       Name Joining_Date
7      HANK   2015-09-14
3     DAVID   2016-08-01
2   CHARLIE   2017-05-19
9      JACK   2017-12-05
1       BOB   2018-07-23
5     FRANK   2018-11-03
0     ALICE   2019-03-15
8       IVY   2019-10-10
4       EVE   2020-01-12
6     GRACE   2021-06-21
10      MAX   2022-06-21

In [41]:
print('Department with most quantity of employees')

dep_counts = df['Department'].value_counts()

max_count = dep_counts.max()

top_deps = dep_counts[dep_counts == max_count].index.to_list()

top_deps

Department with most quantity of employees

['IT']

In [42]:
print('Total salary sum per department')

df.groupby('Department')['Annual_Salary'].sum()

Total salary sum per department

Department
FINANCE      213000
HR           115000
IT           230000
MARKETING    140000
Name: Annual_Salary, dtype: int64

In [43]:
print('Convert Joining_Date to datetime')

df['Joining_Date'] = pd.to_datetime(df['Joining_Date'])
df

Convert Joining_Date to datetime

    ID     Name  Age Department  Annual_Salary Joining_Date
0    1    ALICE   25         HR          50000   2019-03-15
1    2      BOB   30         IT          60000   2018-07-23
2    3  CHARLIE   35    FINANCE          70000   2017-05-19
3    4    DAVID   40         IT          80000   2016-08-01
4    5      EVE   29         HR          65000   2020-01-12
5    6    FRANK   33    FINANCE          72000   2018-11-03
6    7    GRACE   28  MARKETING          48000   2021-06-21
7    8     HANK   45         IT          90000   2015-09-14
8    9      IVY   31    FINANCE          71000   2019-10-10
9   10     JACK   22  MARKETING          92000   2017-12-05
10  10      MAX   22         IT              0   2022-06-21

In [44]:
print('Most recent joining employee')

df.loc[df['Joining_Date'] == df['Joining_Date'].max(), ['Name', 'Joining_Date']]

Most recent joining employee

   Name Joining_Date
10  MAX   2022-06-21

In [45]:
print('The two employees with the lowest Salary')

df[['Name', 'Annual_Salary']].nsmallest(2, ['Annual_Salary'])

The two employees with the lowest Salary

     Name  Annual_Salary
10    MAX              0
6   GRACE          48000

In [46]:
print('Remplace HR department for Human Resources')

df_HR = df.copy()

df_HR['Department'] = df_HR['Department'].replace('HR', 'Human Resources')

df_HR

Remplace HR department for Human Resources

    ID     Name  Age       Department  Annual_Salary Joining_Date
0    1    ALICE   25  Human Resources          50000   2019-03-15
1    2      BOB   30               IT          60000   2018-07-23
2    3  CHARLIE   35          FINANCE          70000   2017-05-19
3    4    DAVID   40               IT          80000   2016-08-01
4    5      EVE   29  Human Resources          65000   2020-01-12
5    6    FRANK   33          FINANCE          72000   2018-11-03
6    7    GRACE   28        MARKETING          48000   2021-06-21
7    8     HANK   45               IT          90000   2015-09-14
8    9      IVY   31          FINANCE          71000   2019-10-10
9   10     JACK   22        MARKETING          92000   2017-12-05
10  10      MAX   22               IT              0   2022-06-21

In [47]:
print('Remplace HR department for Human Resources with \"loc\"')

df_HR = df.copy()

df_HR.loc[df['Department'] == 'HR'] = 'Human Resources'

df_HR

Remplace HR department for Human Resources with "loc"

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_26172\3727089451.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Human Resources' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_HR.loc[df['Department'] == 'HR'] = 'Human Resources'
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_26172\3727089451.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Human Resources' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_HR.loc[df['Department'] == 'HR'] = 'Human Resources'
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_26172\3727089451.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Human Resources' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_HR.loc[df['Department'] == 'HR'] = 'Human Resources'
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_26172\3727089451.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Human Resources' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  df_HR.loc[df['Department'] == 'HR'] = 'Human Resources'

,ID,Name,Age,Department,Annual_Salary,Joining_Date
0,Human Resources,Human Resources,Human Resources,Human Resources,Human Resources,Human Resources
1,2,BOB,30,IT,60000,2018-07-23 00:00:00
2,3,CHARLIE,35,FINANCE,70000,2017-05-19 00:00:00
3,4,DAVID,40,IT,80000,2016-08-01 00:00:00
4,Human Resources,Human Resources,Human Resources,Human Resources,Human Resources,Human Resources
5,6,FRANK,33,FINANCE,72000,2018-11-03 00:00:00
6,7,GRACE,28,MARKETING,48000,2021-06-21 00:00:00
7,8,HANK,45,IT,90000,2015-09-14 00:00:00
8,9,IVY,31,FINANCE,71000,2019-10-10 00:00:00
9,10,JACK,22,MARKETING,92000,2017-12-05 00:00:00
10,10,MAX,22,IT,0,2022-06-21 00:00:00

In [48]:
print('New coulumn with monthy salary')

df['Monthly_Salary'] = df['Annual_Salary'].apply(lambda x: x/12)

df.insert(df.columns.get_loc('Annual_Salary') + 1, 'Monthly_Salary', df.pop('Monthly_Salary'))

df

New coulumn with monthy salary

    ID     Name  Age Department  Annual_Salary  Monthly_Salary Joining_Date
0    1    ALICE   25         HR          50000     4166.666667   2019-03-15
1    2      BOB   30         IT          60000     5000.000000   2018-07-23
2    3  CHARLIE   35    FINANCE          70000     5833.333333   2017-05-19
3    4    DAVID   40         IT          80000     6666.666667   2016-08-01
4    5      EVE   29         HR          65000     5416.666667   2020-01-12
5    6    FRANK   33    FINANCE          72000     6000.000000   2018-11-03
6    7    GRACE   28  MARKETING          48000     4000.000000   2021-06-21
7    8     HANK   45         IT          90000     7500.000000   2015-09-14
8    9      IVY   31    FINANCE          71000     5916.666667   2019-10-10
9   10     JACK   22  MARKETING          92000     7666.666667   2017-12-05
10  10      MAX   22         IT              0        0.000000   2022-06-21

In [49]:
print('Unique departments')

print(df['Department'].unique())

Unique departments
['HR' 'IT' 'FINANCE' 'MARKETING']

In [50]:
print('Years worked till today')


df['Worked_Years'] = df['Joining_Date'].apply(lambda x: (datetime.today() - x).days/ 365.25)

df[['Name', 'Joining_Date', 'Worked_Years']]

Years worked till today

       Name Joining_Date  Worked_Years
0     ALICE   2019-03-15      6.464066
1       BOB   2018-07-23      7.107461
2   CHARLIE   2017-05-19      8.284736
3     DAVID   2016-08-01      9.081451
4       EVE   2020-01-12      5.634497
5     FRANK   2018-11-03      6.825462
6     GRACE   2021-06-21      4.194387
7      HANK   2015-09-14      9.963039
8       IVY   2019-10-10      5.891855
9      JACK   2017-12-05      7.737166
10      MAX   2022-06-21      3.195072

In [51]:
print('Max and mean salary per deparment')


df.groupby('Department')['Annual_Salary'].agg(['min', 'mean', 'max'])

Max and mean salary per deparment

              min     mean    max
Department
FINANCE     70000  71000.0  72000
HR          50000  57500.0  65000
IT              0  57500.0  90000
MARKETING   48000  70000.0  92000

In [52]:
print('Oldest employee per department')

oldest_index = df.groupby('Department')['Age'].idxmax()
df.loc[oldest_index, ['Department', 'Name', 'Age']]

Oldest employee per department

  Department     Name  Age
2    FINANCE  CHARLIE   35
4         HR      EVE   29
7         IT     HANK   45
6  MARKETING    GRACE   28

In [53]:
print('Employees which names start with \"A\"')

df[df['Name'].str.startswith('A')]['Name']

Employees which names start with "A"

0    ALICE
Name: Name, dtype: object

In [54]:
print('Export Name, Department and Salary to CSV')

df_selected = df[['Name', 'Department', 'Annual_Salary']]

df_selected.to_csv('employees_reduced.csv')

Export Name, Department and Salary to CSV

In [55]:
print('Verify if there is a salary upper 85000')

df[df['Annual_Salary'] > 85000][['Name', 'Annual_Salary']]

Verify if there is a salary upper 85000

   Name  Annual_Salary
7  HANK          90000
9  JACK          92000

In [56]:
print('Count how many employees between 30 and 40 years')

age_30_40 = df[df['Age'].between(30,40)]['Age'].count()
print(age_30_40)

Count how many employees between 30 and 40 years
5

In [57]:
df

,ID,Name,Age,Department,Annual_Salary,Monthly_Salary,Joining_Date,Worked_Years
0,1,ALICE,25,HR,50000,4166.666667,2019-03-15,6.464066
1,2,BOB,30,IT,60000,5000.000000,2018-07-23,7.107461
2,3,CHARLIE,35,FINANCE,70000,5833.333333,2017-05-19,8.284736
3,4,DAVID,40,IT,80000,6666.666667,2016-08-01,9.081451
4,5,EVE,29,HR,65000,5416.666667,2020-01-12,5.634497
5,6,FRANK,33,FINANCE,72000,6000.000000,2018-11-03,6.825462
6,7,GRACE,28,MARKETING,48000,4000.000000,2021-06-21,4.194387
7,8,HANK,45,IT,90000,7500.000000,2015-09-14,9.963039
8,9,IVY,31,FINANCE,71000,5916.666667,2019-10-10,5.891855
9,10,JACK,22,MARKETING,92000,7666.666667,2017-12-05,7.737166
10,10,MAX,22,IT,0,0.000000,2022-06-21,3.195072

In [58]:
print('Rows department, mean Age and Salary columns')


df.groupby('Department')[['Age', 'Annual_Salary']].mean()

Rows department, mean Age and Salary columns

              Age  Annual_Salary
Department
FINANCE     33.00        71000.0
HR          27.00        57500.0
IT          34.25        57500.0
MARKETING   25.00        70000.0

In [59]:
print('Employees who joined before 2018')

df[df['Joining_Date'].dt.year < 2018][['Name', 'Joining_Date']]

Employees who joined before 2018

      Name Joining_Date
2  CHARLIE   2017-05-19
3    DAVID   2016-08-01
7     HANK   2015-09-14
9     JACK   2017-12-05

In [60]:
print('DataFrame with only Finance employees')

df[df['Department'].str.strip().str.upper() == 'HR']

DataFrame with only Finance employees

,ID,Name,Age,Department,Annual_Salary,Monthly_Salary,Joining_Date,Worked_Years
0,1,ALICE,25,HR,50000,4166.666667,2019-03-15,6.464066
4,5,EVE,29,HR,65000,5416.666667,2020-01-12,5.634497

In [61]:
print('Dict key department and value employee number')

df_dep = df.groupby('Department')['Department'].count()
df_dep.index[0]

dict_dep = df_dep.to_dict()

dict_dep

Dict key department and value employee number

{'FINANCE': 3, 'HR': 2, 'IT': 4, 'MARKETING': 2}

In [62]:

print('Find the youngest employee in each department')


### This method has a problem, it only will take the first min Age, if two or more people have same min age, just one will be taken

ids = df.groupby('Department')['Age'].idxmin().values

df.iloc[ids][['Department', 'Name', 'Age']]

Find the youngest employee in each department

   Department   Name  Age
8     FINANCE    IVY   31
0          HR  ALICE   25
10         IT    MAX   22
9   MARKETING   JACK   22

In [63]:
print('Find the youngest employee in each department - second')

### This method has a problem, it only will take the first min Age, if two or more people have same min age, just one will be taken

df.groupby('Department')['Age'].nsmallest(1)

Find the youngest employee in each department - second

Department
FINANCE     8     31
HR          0     25
IT          10    22
MARKETING   9     22
Name: Age, dtype: int64

In [64]:
print('Find the youngest employee in each department - third')

min_age_per_dept = df.groupby('Department')['Age'].transform('min')

print(min_age_per_dept)

df[df['Age'] == min_age_per_dept][['Department', 'Name', 'Age']].sort_values('Department')

Find the youngest employee in each department - third
0     25
1     22
2     31
3     22
4     25
5     31
6     22
7     22
8     31
9     22
10    22
Name: Age, dtype: int64

   Department   Name  Age
8     FINANCE    IVY   31
0          HR  ALICE   25
10         IT    MAX   22
9   MARKETING   JACK   22

In [65]:
print('Show the employees who earn more than their department’s average salary')

dep_mean = df.groupby('Department')['Annual_Salary'].mean()

print(dep_mean)


df_merged = df.merge(dep_mean, on = 'Department')


df_merged = df_merged.rename(columns={'Annual_Salary_x': 'Annual_Salary', 'Annual_Salary_y': 'Dep_Avg_Salary'})

df_merged[df_merged['Annual_Salary'] > df_merged['Dep_Avg_Salary']][['Name', 'Department', 'Annual_Salary', 'Dep_Avg_Salary']]

Show the employees who earn more than their department’s average salary
Department
FINANCE      71000.0
HR           57500.0
IT           57500.0
MARKETING    70000.0
Name: Annual_Salary, dtype: float64

    Name Department  Annual_Salary  Dep_Avg_Salary
1    BOB         IT          60000         57500.0
3  DAVID         IT          80000         57500.0
4    EVE         HR          65000         57500.0
5  FRANK    FINANCE          72000         71000.0
7   HANK         IT          90000         57500.0
9   JACK  MARKETING          92000         70000.0

In [66]:
print('Show the employees who earn more than their department’s average salary - BETTER')


df['Dep_Avg_Salary'] = df.groupby('Department')['Annual_Salary'].transform('mean')
df[df['Annual_Salary'] > df['Dep_Avg_Salary']][['Name', 'Department', 'Annual_Salary', 'Dep_Avg_Salary']]

Show the employees who earn more than their department’s average salary - BETTER

    Name Department  Annual_Salary  Dep_Avg_Salary
1    BOB         IT          60000         57500.0
3  DAVID         IT          80000         57500.0
4    EVE         HR          65000         57500.0
5  FRANK    FINANCE          72000         71000.0
7   HANK         IT          90000         57500.0
9   JACK  MARKETING          92000         70000.0