In [7]:
import pandas as pd

In [8]:
DF1 = pd.DataFrame({'NOMBRE':['Jose', 'Max'],
'CARRERAS': ['Economia', 'Arquitectura'],
'EDAD': [23,26]}).set_index('NOMBRE')

In [9]:
DF2 = pd.DataFrame({'NOMBRE':['Aurorra', 'Maria'],
'CARRERAS': ['Medicina', 'Informatica'],
'EDAD': [22,28]}).set_index('NOMBRE')

In [11]:
DF = pd.concat([DF1,DF2])

In [12]:
DF1

            CARRERAS  EDAD
NOMBRE
Jose        Economia    23
Max     Arquitectura    26

In [13]:
DF2

            CARRERAS  EDAD
NOMBRE
Aurorra     Medicina    22
Maria    Informatica    28

In [14]:
DF

             CARRERAS  EDAD
NOMBRE
Jose         Economia    23
Max      Arquitectura    26
Aurorra      Medicina    22
Maria     Informatica    28