In [1]:
import pandas as pd

In [11]:
DF1 = pd.DataFrame({'AUTOS': ['Nissan', 'Ford', 'Audi'],
'COLOR': ['blanco', 'Azul', 'Rojo']}).set_index('AUTOS')

In [12]:
DF2 = pd.DataFrame({'AUTOS': ['Nissan', 'Ford', 'Audi'],
'MODELO': ['2018', '2020', '2022']}).set_index('AUTOS')

In [13]:
DF1

         COLOR
AUTOS
Nissan  blanco
Ford      Azul
Audi      Rojo

In [14]:
DF2

       MODELO
AUTOS
Nissan   2018
Ford     2020
Audi     2022

In [15]:
DF = pd.concat([DF1, DF2], axis=1)

In [16]:
DF

         COLOR MODELO
AUTOS
Nissan  blanco   2018
Ford      Azul   2020
Audi      Rojo   2022