In [50]:
import pandas as pd

In [51]:
df = pd.read_excel('..\datasets\estudiantes.xlsx')

In [52]:
df.to_csv('..\datasets\estudiantes.csv', index=None, header=True)

In [53]:
df.iloc[1,3]

'Informatica'

In [54]:
df.iloc[2,:3]

NOMBRE    Raul
EDAD        26
GENERO       M
Name: 2, dtype: object

In [55]:
df.loc[:3, ('NOMBRE', 'EDAD')]

    NOMBRE  EDAD
0   Victor    28
1   Josefa    23
2     Raul    26
3  Mariana    27

In [56]:
df.iloc[1,:3]

NOMBRE    Josefa
EDAD          23
GENERO         F
Name: 1, dtype: object

In [57]:
df['TURNO'] = pd.Series(['tarde', 'noche', 'tarde','noche','noche','tarde'])

In [58]:
df

    NOMBRE  EDAD GENERO       CARRERA SEMESTRE  TURNO
0   Victor    28      M     Auditoria  Primero  tarde
1   Josefa    23      F   Informatica  Primero  noche
2     Raul    26      M       Derecho   Quinto  tarde
3  Mariana    27      F    Informtica  Septimo  noche
4  Rodrigo    22      M       Derecho  Tercero  noche
5  Gustavo    25      M  Arquitectura  Septimo  tarde
6     Lucy    23      F   Informatica  Primero    NaN
7    Sofia    24      F      Economia   Noveno    NaN

In [59]:
SEMESTRE = df.pop('SEMESTRE')

In [60]:
df

    NOMBRE  EDAD GENERO       CARRERA  TURNO
0   Victor    28      M     Auditoria  tarde
1   Josefa    23      F   Informatica  noche
2     Raul    26      M       Derecho  tarde
3  Mariana    27      F    Informtica  noche
4  Rodrigo    22      M       Derecho  noche
5  Gustavo    25      M  Arquitectura  tarde
6     Lucy    23      F   Informatica    NaN
7    Sofia    24      F      Economia    NaN

In [61]:
df.loc[len(df)] = ['Carlos', 27, 'M', 'Sociologia', 'tarde']

In [62]:
df

    NOMBRE  EDAD GENERO       CARRERA  TURNO
0   Victor    28      M     Auditoria  tarde
1   Josefa    23      F   Informatica  noche
2     Raul    26      M       Derecho  tarde
3  Mariana    27      F    Informtica  noche
4  Rodrigo    22      M       Derecho  noche
5  Gustavo    25      M  Arquitectura  tarde
6     Lucy    23      F   Informatica    NaN
7    Sofia    24      F      Economia    NaN
8   Carlos    27      M    Sociologia  tarde

In [63]:
df.drop([1,2])

    NOMBRE  EDAD GENERO       CARRERA  TURNO
0   Victor    28      M     Auditoria  tarde
3  Mariana    27      F    Informtica  noche
4  Rodrigo    22      M       Derecho  noche
5  Gustavo    25      M  Arquitectura  tarde
6     Lucy    23      F   Informatica    NaN
7    Sofia    24      F      Economia    NaN
8   Carlos    27      M    Sociologia  tarde

In [64]:
df[(df['GENERO']=='F') & (df['EDAD'] >= 22)]

    NOMBRE  EDAD GENERO      CARRERA  TURNO
1   Josefa    23      F  Informatica  noche
3  Mariana    27      F   Informtica  noche
6     Lucy    23      F  Informatica    NaN
7    Sofia    24      F     Economia    NaN

In [65]:
df

    NOMBRE  EDAD GENERO       CARRERA  TURNO
0   Victor    28      M     Auditoria  tarde
1   Josefa    23      F   Informatica  noche
2     Raul    26      M       Derecho  tarde
3  Mariana    27      F    Informtica  noche
4  Rodrigo    22      M       Derecho  noche
5  Gustavo    25      M  Arquitectura  tarde
6     Lucy    23      F   Informatica    NaN
7    Sofia    24      F      Economia    NaN
8   Carlos    27      M    Sociologia  tarde

In [66]:
df.drop([8])

    NOMBRE  EDAD GENERO       CARRERA  TURNO
0   Victor    28      M     Auditoria  tarde
1   Josefa    23      F   Informatica  noche
2     Raul    26      M       Derecho  tarde
3  Mariana    27      F    Informtica  noche
4  Rodrigo    22      M       Derecho  noche
5  Gustavo    25      M  Arquitectura  tarde
6     Lucy    23      F   Informatica    NaN
7    Sofia    24      F      Economia    NaN

In [67]:
df.sort_values('CARRERA')

    NOMBRE  EDAD GENERO       CARRERA  TURNO
5  Gustavo    25      M  Arquitectura  tarde
0   Victor    28      M     Auditoria  tarde
2     Raul    26      M       Derecho  tarde
4  Rodrigo    22      M       Derecho  noche
7    Sofia    24      F      Economia    NaN
1   Josefa    23      F   Informatica  noche
6     Lucy    23      F   Informatica    NaN
3  Mariana    27      F    Informtica  noche
8   Carlos    27      M    Sociologia  tarde

In [68]:
df.sort_values('EDAD')

    NOMBRE  EDAD GENERO       CARRERA  TURNO
4  Rodrigo    22      M       Derecho  noche
1   Josefa    23      F   Informatica  noche
6     Lucy    23      F   Informatica    NaN
7    Sofia    24      F      Economia    NaN
5  Gustavo    25      M  Arquitectura  tarde
2     Raul    26      M       Derecho  tarde
3  Mariana    27      F    Informtica  noche
8   Carlos    27      M    Sociologia  tarde
0   Victor    28      M     Auditoria  tarde

In [69]:
df.dropna()

    NOMBRE  EDAD GENERO       CARRERA  TURNO
0   Victor    28      M     Auditoria  tarde
1   Josefa    23      F   Informatica  noche
2     Raul    26      M       Derecho  tarde
3  Mariana    27      F    Informtica  noche
4  Rodrigo    22      M       Derecho  noche
5  Gustavo    25      M  Arquitectura  tarde
8   Carlos    27      M    Sociologia  tarde