In [2]:
import pandas as pd

In [3]:
DF1 = pd.DataFrame({'AUTOS': ['Nissan', 'Ford', 'Audi'],
'COLOR': ['blanco', 'Azul', 'Rojo']})

In [6]:
DF2 = pd.DataFrame({'AUTOS': ['Toyota', 'Ford', 'Audi'],
'MODELO': ['2018', '2020', '2022']})

In [8]:
pd.merge(DF1, DF2, on='AUTOS', how='outer')

    AUTOS   COLOR MODELO
0    Audi    Rojo   2022
1    Ford    Azul   2020
2  Nissan  blanco    NaN
3  Toyota     NaN   2018

In [9]:
pd.merge(DF1, DF2, on='AUTOS', how='left')

    AUTOS   COLOR MODELO
0  Nissan  blanco    NaN
1    Ford    Azul   2020
2    Audi    Rojo   2022

In [10]:
pd.merge(DF1, DF2, on='AUTOS', how='right')

    AUTOS COLOR MODELO
0  Toyota   NaN   2018
1    Ford  Azul   2020
2    Audi  Rojo   2022