In [5]:
import pandas as pd
import numpy as np

In [3]:
df =  pd.read_csv('..\datasets\ModalidadVirtual.csv')

In [4]:
df

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...,...
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [7]:
print("First n rows")
n = 3
df.head(n)

First n rows

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí

In [8]:
print("Last n rows")
df.tail(n)

Last n rows

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [9]:
print('Summary of DataFrame')
df.info()

Summary of DataFrame
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222 entries, 0 to 221
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  222 non-null    int64
 1   time        222 non-null    object
 2   carrera     222 non-null    object
 3   acepta      222 non-null    object
 4   positivo    222 non-null    object
 5   negativo    222 non-null    object
 6   edad        222 non-null    int64
 7   sexo        222 non-null    object
 8   trabajo     222 non-null    object
dtypes: int64(2), object(7)
memory usage: 15.7+ KB

In [12]:
print('Dimensions of DataFrame.')
print(df.shape)

Dimensions of DataFrame.
(222, 9)

In [13]:
print('Statistics summary')
df.describe()

Statistics summary

       Unnamed: 0        edad
count  222.000000  222.000000
mean   119.896396   28.166667
std     67.424522    7.556374
min      0.000000   17.000000
25%     63.250000   22.000000
50%    121.500000   27.000000
75%    177.750000   33.000000
max    234.000000   54.000000

In [17]:
print('Column data types')
print(df.dtypes)

Column data types
Unnamed: 0     int64
time          object
carrera       object
acepta        object
positivo      object
negativo      object
edad           int64
sexo          object
trabajo       object
dtype: object

In [21]:
print('Select columns')
df[['edad', 'sexo']]

Select columns

     edad    sexo
0      20  Hombre
1      26  Hombre
2      20   Mujer
3      18   Mujer
4      39  Hombre
..    ...     ...
217    19   Mujer
218    23   Mujer
219    25  Hombre
220    20   Mujer
221    23  Hombre

[222 rows x 2 columns]

In [27]:
print('Label-based selection - unique row')
row_0 = 0
row_1 = 1
print(df.loc[row_0])
df.loc[row_1]

Label-based selection - unique row
Unnamed: 0                                         0
time                                      2020-11-08
carrera                       Ingeniería de Sistemas
acepta                                            Si
positivo                           Horario flexible.
negativo      Contacto Personal Docente-Estudiantil.
edad                                              20
sexo                                          Hombre
trabajo                                     Eventual
Name: 0, dtype: object

Unnamed: 0                                         1
time                                      2020-11-08
carrera                                   Psicología
acepta                                            Si
positivo               Acceso desde cualquier lugar.
negativo      Contacto Personal Docente-Estudiantil.
edad                                              26
sexo                                          Hombre
trabajo                                     Eventual
Name: 1, dtype: object

In [31]:
print('Label-based selection - rows list')

df.loc[[0,1,2]]

Label-based selection - rows list

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí

In [33]:
print('Label-based selection - rows range')

df.loc[0:2]

Label-based selection - rows range

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí

In [34]:
print('Label-based selection - rows range, selected columns')

df.loc[0:2, ['carrera', 'acepta', 'time']]

Label-based selection - rows range, selected columns

                  carrera acepta        time
0  Ingeniería de Sistemas     Si  2020-11-08
1              Psicología     Si  2020-11-08
2  Ingeniería de Sistemas     Si  2020-11-08

In [ ]:
print('Integer-location based selection')

df.iloc[0,2]  #  0 ---> row 0   3 ---> column 3

Integer-location based selection

'Ingeniería de Sistemas'

In [36]:
print('Set coulumn as index')

df_reset = df.reset_index()
df_reset

Set coulumn as index

,index,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...,...,...
217,217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [42]:
print('Sort rows by values')

df_sorted_age = df.sort_values("edad", ascending=True)
df_sorted_age

Sort rows by values

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
98,109,2020-11-14,Contaduría Pública,Si,Horario flexible.,Conexión a internet.,17,Hombre,Sí
86,96,2020-11-13,Ciencias de la Educación,Si,Acceso desde cualquier lugar.,Conexión a internet.,17,Mujer,No
75,85,2020-11-10,Trabajo Social,Si,Horario flexible.,Conexión a internet.,17,Mujer,Sí
74,84,2020-11-10,Otra,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,17,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
...,...,...,...,...,...,...,...,...,...
25,27,2020-11-09,Ciencias de la Educación,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,46,Hombre,Sí
141,153,2020-11-22,Comercio Internacional,Si,Horario flexible.,Conexión a internet.,47,Mujer,Sí
85,95,2020-11-11,Derecho,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,49,Hombre,Sí
64,73,2020-11-10,Lingüística e Idiomas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",50,Hombre,Sí
114,125,2020-11-19,Lingüística e Idiomas,Si,Horario flexible.,Conexión a internet.,54,Mujer,Sí

In [43]:
print('Sort by index')

df_sorted_index = df_sorted_age.sort_index()
df_sorted_index

Sort by index

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...,...
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [ ]:
print('Group by carrera, get mean edad')

df_groupby_carrera = df.groupby('carrera')['edad'].mean()
df_groupby_carrera

carrera
Administración de Empresas                  25.375000
Artes Plásticas                             30.000000
Ciencias Físicas y Energías Alternativas    26.500000
Ciencias Políticas                          38.666667
Ciencias de la Educación                    26.153846
Comercio Internacional                      28.857143
Contaduría Pública                          29.461538
Derecho                                     32.515152
Economía                                    28.250000
Educación Parvularia                        32.333333
Gestión Turística y Hotelera                23.800000
Historia                                    25.000000
Ingeniería Agronómica                       27.166667
Ingeniería de Sistemas                      26.375000
Lingüística e Idiomas                       34.250000
Nutrición y Dietética                       31.500000
Otra                                        24.192308
Psicología                                  33.076923
Sociología                                  28.000000
Trabajo Social                              23.875000
Name: edad, dtype: float64

In [55]:
print('Group by sexo, count')

df_groupby_carrera = df.groupby('sexo')['sexo'].count()
df_groupby_carrera

Group by sexo, count

sexo
Hombre    120
Mujer     102
Name: sexo, dtype: int64

In [ ]:
print('Group by trabajo')
df_groupby_carrera = df.groupby('trabajo')['trabajo'].count()
df_groupby_carrera

Group by sexo, count trabajo

trabajo
Eventual     53
No           17
Sí          152
Name: trabajo, dtype: int64

In [65]:
print('Print men and women job status')
df_job = df.groupby(['sexo', 'trabajo'])['trabajo'].count()
df_job

Print men and women job status

sexo    trabajo
Hombre  Eventual    31
        No           5
        Sí          84
Mujer   Eventual    22
        No          12
        Sí          68
Name: trabajo, dtype: int64

In [70]:
print('Cound positive aspects')

df_positive = df.groupby('positivo')['positivo'].count()
df_positive

Cound positive aspects

positivo
Acceso desde cualquier lugar.     92
Autonomía.                        18
Horario flexible.                112
Name: positivo, dtype: int64

In [71]:
print('Mean age of women and men by career')

df_mean = df.groupby(['sexo', 'carrera'])['edad'].mean()
df_mean

Mean age of women and men by career

sexo    carrera
Hombre  Administración de Empresas                  25.750000
        Artes Plásticas                             30.000000
        Ciencias Físicas y Energías Alternativas    26.166667
        Ciencias Políticas                          43.000000
        Ciencias de la Educación                    31.000000
        Comercio Internacional                      24.666667
        Contaduría Pública                          33.833333
        Derecho                                     31.058824
        Economía                                    40.000000
        Educación Parvularia                        37.000000
        Gestión Turística y Hotelera                25.000000
        Historia                                    20.000000
        Ingeniería Agronómica                       28.000000
        Ingeniería de Sistemas                      27.738095
        Lingüística e Idiomas                       33.500000
        Nutrición y Dietética                       28.000000
        Otra                                        25.071429
        Psicología                                  34.333333
        Sociología                                  28.000000
Mujer   Administración de Empresas                  25.000000
        Ciencias Físicas y Energías Alternativas    27.500000
        Ciencias Políticas                          30.000000
        Ciencias de la Educación                    23.125000
        Comercio Internacional                      32.000000
        Contaduría Pública                          25.714286
        Derecho                                     34.062500
        Economía                                    24.333333
        Educación Parvularia                        30.000000
        Gestión Turística y Hotelera                19.000000
        Historia                                    30.000000
        Ingeniería Agronómica                       26.750000
        Ingeniería de Sistemas                      22.285714
        Lingüística e Idiomas                       35.000000
        Nutrición y Dietética                       35.000000
        Otra                                        23.166667
        Psicología                                  32.700000
        Trabajo Social                              23.875000
Name: edad, dtype: float64

In [80]:
print("Max, min, mean of age, groub by career")

df_data = df.groupby('carrera')['edad'].agg(['mean', 'std', 'min', 'max'])
df_data

Max, min, mean of age, groub by career

                                               mean        std  min  max
carrera
Administración de Empresas                25.375000   4.565007   19   32
Artes Plásticas                           30.000000  10.000000   20   40
Ciencias Físicas y Energías Alternativas  26.500000   4.566962   18   33
Ciencias Políticas                        38.666667   7.505553   30   43
Ciencias de la Educación                  26.153846   7.925130   17   46
Comercio Internacional                    28.857143  10.056981   20   47
Contaduría Pública                        29.461538   7.676972   17   41
Derecho                                   32.515152   6.524575   20   49
Economía                                  28.250000   7.847505   24   40
Educación Parvularia                      32.333333   4.041452   30   37
Gestión Turística y Hotelera              23.800000   3.898718   19   29
Historia                                  25.000000   7.071068   20   30
Ingeniería Agronómica                     27.166667   6.911343   20   38
Ingeniería de Sistemas                    26.375000   7.533109   18   45
Lingüística e Idiomas                     34.250000  12.464235   19   54
Nutrición y Dietética                     31.500000   4.949747   28   35
Otra                                      24.192308   4.463355   17   31
Psicología                                33.076923   6.277759   21   45
Sociología                                28.000000        NaN   28   28
Trabajo Social                            23.875000   4.517822   17   30

In [81]:
print('Aggregate multiple functions')

df_mul = df.agg({'edad': ['min','mean','max']})
df_mul

Aggregate multiple functions

           edad
min   17.000000
mean  28.166667
max   54.000000

In [85]:
print('Apply function across axis')

df_copy = df.copy()
df_copy['edad mas 10'] = df['edad'].apply(lambda x: x+10)
df_copy

Apply function across axis

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo,edad mas 10
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual,30
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual,36
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí,30
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No,28
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí,49
...,...,...,...,...,...,...,...,...,...,...
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí,29
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No,33
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí,35
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí,30
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí,33

In [91]:
print('Apply function elementwise (entire DataFrame)')

df_str = df[['carrera', 'sexo']].map(str.upper)
df_str

Apply function elementwise (entire DataFrame)

                          carrera    sexo
0          INGENIERÍA DE SISTEMAS  HOMBRE
1                      PSICOLOGÍA  HOMBRE
2          INGENIERÍA DE SISTEMAS   MUJER
3          INGENIERÍA DE SISTEMAS   MUJER
4          INGENIERÍA DE SISTEMAS  HOMBRE
..                            ...     ...
217  GESTIÓN TURÍSTICA Y HOTELERA   MUJER
218        INGENIERÍA DE SISTEMAS   MUJER
219  GESTIÓN TURÍSTICA Y HOTELERA  HOMBRE
220         INGENIERÍA AGRONÓMICA   MUJER
221        COMERCIO INTERNACIONAL  HOMBRE

[222 rows x 2 columns]

In [116]:

print('Check missing values')
filas_con_nulos = df_data[df_data.isnull().any(axis=1)]
print(filas_con_nulos)

Check missing values
            mean  std  min  max
carrera
Sociología  28.0  NaN   28   28

In [117]:
print('Check missing values')

df_fill = df_data = df.fillna(True)
df_fill

Check missing values

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...,...
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [ ]:
print('Drop columns')

df_drop = df.drop('time', axis=1)
df_drop

Drop columns/rows.

,Unnamed: 0,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...
217,230,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [125]:
print('Drop rows.')

df_drop = df.drop(range(0,5), axis=0)
df_drop

Drop rows.

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
5,5,2020-11-08,Ciencias de la Educación,Si,Acceso desde cualquier lugar.,Conexión a internet.,25,Mujer,Sí
6,6,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",18,Hombre,Eventual
7,7,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Sí
8,8,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Sí
9,9,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,25,Hombre,Sí
...,...,...,...,...,...,...,...,...,...
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [128]:
print('Rename columns.')


df_rename = df.rename(columns={"carrera": "career", 'sexo': 'genre'})
df_rename

Rename columns.

,Unnamed: 0,time,career,acepta,positivo,negativo,edad,genre,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...,...
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [129]:
print('Rename columns - upper')

df_upper = df.rename(columns=str.upper)
df_upper

Rename columns - upper

,UNNAMED: 0,TIME,CARRERA,ACEPTA,POSITIVO,NEGATIVO,EDAD,SEXO,TRABAJO
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...,...
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [130]:
print('Rename index ')

df_index = df.rename(index= {0: 'first', 2: 'second'})
df_index

Rename index

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
first,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
second,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...,...
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [131]:
print('Rename using function')

df_func = df.rename(index = lambda x: 'fila_{}'.format(x))
df_func

Rename using function

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
fila_0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
fila_1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
fila_2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
fila_3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
fila_4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...,...
fila_217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
fila_218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
fila_219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
fila_220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
fila_221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [148]:
print('Inner join')

df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "nombre": ["Ana", "Luis", "Marta"]
})

df2 = pd.DataFrame({
    "id": [1, 2, 4],
    "nota": [90, 85, 75]
})

df_inner = pd.merge(df1, df2, on='id', how='inner')

df_inner

Inner join

   id nombre  nota
0   1    Ana    90
1   2   Luis    85

In [149]:
print('Left join')

df_left = pd.merge(df1, df2, on='id', how='left')
df_left

Left join

   id nombre  nota
0   1    Ana  90.0
1   2   Luis  85.0
2   3  Marta   NaN

In [150]:
print('Right join')

df_right = pd.merge(df1, df2, on='id', how='right')
df_right

Right join

   id nombre  nota
0   1    Ana    90
1   2   Luis    85
2   4    NaN    75

In [151]:
print('Outer join')

df_outer = pd.merge(df1, df2, on='id', how='outer')
df_outer

Outer join

   id nombre  nota
0   1    Ana  90.0
1   2   Luis  85.0
2   3  Marta   NaN
3   4    NaN  75.0

In [152]:
print('Merge different columns names')

df3 = pd.DataFrame({
    "codigo": [1, 2, 3],
    "ciudad": ["San José", "Cartago", "Heredia"]
})

df_merge = pd.merge(df1, df3, left_on="id", right_on="codigo", how="inner")
print(df_merge)

Merge different columns names
   id nombre  codigo    ciudad
0   1    Ana       1  San José
1   2   Luis       2   Cartago
2   3  Marta       3   Heredia

In [155]:
print('Concat')

df_concat = pd.concat([df1, df2], axis=1)
df_concat

Concat

   id nombre  id  nota
0   1    Ana   1    90
1   2   Luis   2    85
2   3  Marta   4    75

In [158]:
print('pivot table')

pivot = df.pivot_table(values="edad", index="carrera", aggfunc=np.mean)

pivot

pivot table

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_30112\1117399012.py:3: FutureWarning: The provided callable <function mean at 0x00000121AD616AC0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot = df.pivot_table(values="edad", index="carrera", aggfunc=np.mean)

                                               edad
carrera
Administración de Empresas                25.375000
Artes Plásticas                           30.000000
Ciencias Físicas y Energías Alternativas  26.500000
Ciencias Políticas                        38.666667
Ciencias de la Educación                  26.153846
Comercio Internacional                    28.857143
Contaduría Pública                        29.461538
Derecho                                   32.515152
Economía                                  28.250000
Educación Parvularia                      32.333333
Gestión Turística y Hotelera              23.800000
Historia                                  25.000000
Ingeniería Agronómica                     27.166667
Ingeniería de Sistemas                    26.375000
Lingüística e Idiomas                     34.250000
Nutrición y Dietética                     31.500000
Otra                                      24.192308
Psicología                                33.076923
Sociología                                28.000000
Trabajo Social                            23.875000

In [161]:
print('pivot table')

pivot = df.pivot_table(values="edad", index="sexo", aggfunc=np.mean)

pivot

pivot table

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_30112\891369968.py:3: FutureWarning: The provided callable <function mean at 0x00000121AD616AC0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot = df.pivot_table(values="edad", index="sexo", aggfunc=np.mean)

             edad
sexo
Hombre  28.816667
Mujer   27.401961

In [166]:
print('Frequency count')


print(df['carrera'].value_counts())
print(df['sexo'].value_counts())

Frequency count
carrera
Ingeniería de Sistemas                      56
Derecho                                     33
Otra                                        26
Psicología                                  13
Contaduría Pública                          13
Ciencias de la Educación                    13
Ciencias Físicas y Energías Alternativas     8
Administración de Empresas                   8
Lingüística e Idiomas                        8
Trabajo Social                               8
Comercio Internacional                       7
Ingeniería Agronómica                        6
Gestión Turística y Hotelera                 5
Economía                                     4
Ciencias Políticas                           3
Artes Plásticas                              3
Educación Parvularia                         3
Historia                                     2
Nutrición y Dietética                        2
Sociología                                   1
Name: count, dtype: int64
sexo
Hombre    120
Mujer     102
Name: count, dtype: int64

In [ ]:
print('Unique value counts.')
print(df.nunique())

Unique value counts.
Unnamed: 0    222
time           27
carrera        20
acepta          2
positivo        3
negativo        3
edad           33
sexo            2
trabajo         3
dtype: int64